"""
This type stub file was generated by pyright.
"""

from email.header import Header, decode_header, make_header
from email.message import Message
from typing import Any, cast

METADATA_FIELDS = ...
def json_name(field: str) -> str:
    ...

def msg_to_json(msg: Message) -> dict[str, Any]:
    """Convert a Message object into a JSON-compatible dictionary."""
    ...

