"""
This type stub file was generated by pyright.
"""

import importlib
from collections import namedtuple
from typing import Any
from pip._internal.cli.base_command import Command

"""
Package containing all pip commands
"""
CommandInfo = ...
commands_dict: dict[str, CommandInfo] = ...
def create_command(name: str, **kwargs: Any) -> Command:
    """
    Create an instance of the Command class with the given name.
    """
    ...

def get_similar_commands(name: str) -> str | None:
    """Command name auto-correct."""
    ...

