"""
This type stub file was generated by pyright.
"""

from pyperclip import copy, paste

'''
A croos platform clipboard read/write library.

...well, as I were trying to implement this.
I realize that everything is already in the pyperclip module.

'''

__all__ = ['copy', 'paste']
