"""
This type stub file was generated by pyright.
"""

from kivy.logger import Logger
from kivy.event import EventDispatcher
from kivy.core import core_register_libs
from kivy.resources import resource_find
from kivy.properties import AliasProperty, BooleanProperty, BoundedNumericProperty, NumericProperty, OptionProperty, StringProperty
from kivy.utils import platform
from kivy.setupconfig import USE_SDL2
from sys import float_info
from kivy.lib.gstplayer import GstPlayer

'''
Audio
=====

Load an audio sound and play it with::

    from kivy.core.audio import SoundLoader

    sound = SoundLoader.load('mytest.wav')
    if sound:
        print("Sound found at %s" % sound.source)
        print("Sound is %.3f seconds" % sound.length)
        sound.play()

You should not use the Sound class directly. The class returned by
:func:`SoundLoader.load` will be the best sound provider for that particular
file type, so it might return different Sound classes depending the file type.

Event dispatching and state changes
-----------------------------------

Audio is often processed in parallel to your code. This means you often need to
enter the Kivy :func:`eventloop <kivy.base.EventLoopBase>` in order to allow
events and state changes to be dispatched correctly.

You seldom need to worry about this as Kivy apps typically always
require this event loop for the GUI to remain responsive, but it is good to
keep this in mind when debugging or running in a
`REPL <https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop>`_
(Read-eval-print loop).

.. versionchanged:: 1.10.0
    The pygst and gi providers have been removed.

.. versionchanged:: 1.8.0
    There are now 2 distinct Gstreamer implementations: one using Gi/Gst
    working for both Python 2+3 with Gstreamer 1.0, and one using PyGST
    working only for Python 2 + Gstreamer 0.10.

.. note::

    The core audio library does not support recording audio. If you require
    this functionality, please refer to the
    `audiostream <https://github.com/kivy/audiostream>`_ extension.

'''
__all__ = ('Sound', 'SoundLoader')
class SoundLoader:
    '''Load a sound, using the best loader for the given file type.
    '''
    _classes = ...
    @staticmethod
    def register(classobj): # -> None:
        '''Register a new class to load the sound.'''
        ...
    
    @staticmethod
    def load(filename): # -> None:
        '''Load a sound, and return a Sound() instance.'''
        ...
    


class Sound(EventDispatcher):
    '''Represents a sound to play. This class is abstract, and cannot be used
    directly.

    Use SoundLoader to load a sound.

    :Events:
        `on_play`: None
            Fired when the sound is played.
        `on_stop`: None
            Fired when the sound is stopped.
    '''
    source = ...
    volume = ...
    pitch = ...
    state = ...
    loop = ...
    __events__ = ...
    def on_source(self, instance, filename): # -> None:
        ...
    
    def get_pos(self): # -> Literal[0]:
        '''
        Returns the current position of the audio file.
        Returns 0 if not playing.

        .. versionadded:: 1.4.1
        '''
        ...
    
    length = ...
    def load(self): # -> None:
        '''Load the file into memory.'''
        ...
    
    def unload(self): # -> None:
        '''Unload the file from memory.'''
        ...
    
    def play(self): # -> None:
        '''Play the file.'''
        ...
    
    def stop(self): # -> None:
        '''Stop playback.'''
        ...
    
    def seek(self, position): # -> None:
        '''Go to the <position> (in seconds).

        .. note::
            Most sound providers cannot seek when the audio is stopped.
            Play then seek.
        '''
        ...
    
    def on_play(self): # -> None:
        ...
    
    def on_stop(self): # -> None:
        ...
    


audio_libs = ...
if platform == 'android':
    ...
else:
    ...
if USE_SDL2:
    ...
else:
    ...
libs_loaded = ...
