"""
This type stub file was generated by pyright.
"""

from ._util.gtk import GtkIcon

class Icon(GtkIcon):
    HAS_DEFAULT_ACTION = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


