"""
This type stub file was generated by pyright.
"""

import Foundation
import objc
from . import _base

class Icon(_base.Icon):
    _ACTION_SELECTOR = ...
    _MENU_ITEM_SELECTOR = ...
    HAS_DEFAULT_ACTION = ...
    HAS_MENU_RADIO = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class IconDelegate(Foundation.NSObject):
    @objc.namedSelector(Icon._ACTION_SELECTOR)
    def activate_button(self, sender): # -> None:
        ...
    
    @objc.namedSelector(Icon._MENU_ITEM_SELECTOR)
    def activate_menu_item(self, sender): # -> None:
        ...
    


