"""
This type stub file was generated by pyright.
"""

from . import _base

class Icon(_base.Icon):
    _HWND_TO_ICON = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def __del__(self): # -> None:
        ...
    


