"""
This type stub file was generated by pyright.
"""

from pip._internal.utils import _log

def main(args: list[str] | None = ...) -> int:
    """This is preserved for old console scripts that may still be referencing
    it.

    For additional details, see https://github.com/pypa/pip/issues/7498.
    """
    ...

