"""
This type stub file was generated by pyright.
"""

from kivy.uix.behaviors import CompoundSelectionBehavior

'''
RecycleView Layouts
===================

.. versionadded:: 1.10.0

The Layouts handle the presentation of views for the
:class:`~kivy.uix.recycleview.RecycleView`.

.. warning::
    This module is highly experimental, its API may change in the future and
    the documentation is not complete at this time.
'''
class LayoutChangeException(Exception):
    ...


class LayoutSelectionBehavior(CompoundSelectionBehavior):
    '''The :class:`LayoutSelectionBehavior` can be combined with
    :class:`RecycleLayoutManagerBehavior` to allow its derived classes
    selection behaviors similarly to how
    :class:`~kivy.uix.behaviors.compoundselection.CompoundSelectionBehavior`
    can be used to add selection behaviors to normal layout.

    :class:`RecycleLayoutManagerBehavior` manages its children
    differently than normal layouts or widgets so this class adapts
    :class:`~kivy.uix.behaviors.compoundselection.CompoundSelectionBehavior`
    based selection to work with :class:`RecycleLayoutManagerBehavior` as well.

    Similarly to
    :class:`~kivy.uix.behaviors.compoundselection.CompoundSelectionBehavior`,
    one can select using the keyboard or touch, which calls :meth:`select_node`
    or :meth:`deselect_node`, or one can call these methods directly. When a
    item is selected or deselected :meth:`apply_selection` is called. See
    :meth:`apply_selection`.


    '''
    key_selection = ...
    _selectable_nodes = ...
    _nodes_map = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def compute_sizes_from_data(self, data, flags):
        ...
    
    def get_selectable_nodes(self): # -> list[int]:
        ...
    
    def get_index_of_node(self, node, selectable_nodes): # -> int:
        ...
    
    def goto_node(self, key, last_node, last_node_idx): # -> tuple[Any, Any | int]:
        ...
    
    def select_node(self, node): # -> None:
        ...
    
    def deselect_node(self, node): # -> None:
        ...
    
    def apply_selection(self, index, view, is_selected): # -> None:
        '''Applies the selection to the view. This is called internally when
        a view is displayed and it needs to be shown as selected or as not
        selected.

        It is called when :meth:`select_node` or :meth:`deselect_node` is
        called or when a view needs to be refreshed. Its function is purely to
        update the view to reflect the selection state. So the function may be
        called multiple times even if the selection state may not have changed.

        If the view is a instance of
        :class:`~kivy.uix.recycleview.views.RecycleDataViewBehavior`, its
        :meth:`~kivy.uix.recycleview.views.RecycleDataViewBehavior.\
apply_selection` method will be called every time the view needs to refresh
        the selection state. Otherwise, the this method is responsible
        for applying the selection.

        :Parameters:

            `index`: int
                The index of the data item that is associated with the view.
            `view`: widget
                The widget that is the view of this data item.
            `is_selected`: bool
                Whether the item is selected.
        '''
        ...
    
    def refresh_view_layout(self, index, layout, view, viewport): # -> None:
        ...
    


class RecycleLayoutManagerBehavior:
    """A RecycleLayoutManagerBehavior is responsible for positioning views into
    the :attr:`RecycleView.data` within a :class:`RecycleView`. It adds new
    views into the data when it becomes visible to the user, and removes them
    when they leave the visible area.
    """
    viewclass = ...
    key_viewclass = ...
    recycleview = ...
    asked_sizes = ...
    def attach_recycleview(self, rv): # -> None:
        ...
    
    def detach_recycleview(self): # -> None:
        ...
    
    def compute_sizes_from_data(self, data, flags): # -> None:
        ...
    
    def compute_layout(self, data, flags): # -> None:
        ...
    
    def compute_visible_views(self, data, viewport): # -> None:
        '''`viewport` is in coordinates of the layout manager.
        '''
        ...
    
    def set_visible_views(self, indices, data, viewport): # -> None:
        '''`viewport` is in coordinates of the layout manager.
        '''
        ...
    
    def refresh_view_layout(self, index, layout, view, viewport): # -> None:
        '''`See :meth:`~kivy.uix.recycleview.views.RecycleDataAdapter.\
refresh_view_layout`.
        '''
        ...
    
    def get_view_index_at(self, pos): # -> None:
        """Return the view `index` on which position, `pos`, falls.

        `pos` is in coordinates of the layout manager.
        """
        ...
    
    def remove_views(self): # -> None:
        ...
    
    def remove_view(self, view, index): # -> None:
        ...
    
    def clear_layout(self): # -> None:
        ...
    
    def goto_view(self, index): # -> None:
        '''Moves the views so that the view corresponding to `index` is
        visible.
        '''
        ...
    
    def on_viewclass(self, instance, value): # -> None:
        ...
    


