"""
This type stub file was generated by pyright.
"""

from kivy.event import EventDispatcher

'''
RecycleView Views
=================

.. versionadded:: 1.10.0

The adapter part of the RecycleView which together with the layout is the
view part of the model-view-controller pattern.

The view module handles converting the data to a view using the adapter class
which is then displayed by the layout. A view can be any Widget based class.
However, inheriting from RecycleDataViewBehavior adds methods for converting
the data to a view.

TODO:
    * Make view caches specific to each view class type.

'''
__all__ = ('RecycleDataViewBehavior', 'RecycleKVIDsDataViewBehavior', 'RecycleDataAdapter')
_view_base_cache = ...
_cached_views = ...
_cache_count = ...
_max_cache_size = ...
class RecycleDataViewBehavior:
    '''A optional base class for data views (:attr:`RecycleView`.viewclass).
    If a view inherits from this class, the class's functions will be called
    when the view needs to be updated due to a data change or layout update.
    '''
    def refresh_view_attrs(self, rv, index, data): # -> None:
        '''Called by the :class:`RecycleAdapter` when the view is initially
        populated with the values from the `data` dictionary for this item.

        Any pos or size info should be removed because they are set
        subsequently with :attr:`refresh_view_layout`.

        :Parameters:

            `rv`: :class:`RecycleView` instance
                The :class:`RecycleView` that caused the update.
            `data`: dict
                The data dict used to populate this view.
        '''
        ...
    
    def refresh_view_layout(self, rv, index, layout, viewport): # -> None:
        '''Called when the view's size is updated by the layout manager,
        :class:`RecycleLayoutManagerBehavior`.

        :Parameters:

            `rv`: :class:`RecycleView` instance
                The :class:`RecycleView` that caused the update.
            `viewport`: 4-tuple
                The coordinates of the bottom left and width height in layout
                manager coordinates. This may be larger than this view item.

        :raises:
            `LayoutChangeException`: If the sizing or data changed during a
            call to this method, raising a `LayoutChangeException` exception
            will force a refresh. Useful when data changed and we don't want
            to layout further since it'll be overwritten again soon.
        '''
        ...
    
    def apply_selection(self, rv, index, is_selected): # -> None:
        ...
    


class RecycleKVIDsDataViewBehavior(RecycleDataViewBehavior):
    """Similar to :class:`RecycleDataViewBehavior`, except that the data keys
    can signify properties of an object named with an id in the root KV rule.

    E.g. given a KV rule::

        <MyRule@RecycleKVIDsDataViewBehavior+BoxLayout>:
            Label:
                id: name
            Label:
                id: value

    Then setting the data list with
    ``rv.data = [{'name.text': 'Kivy user', 'value.text': '12'}]`` would
    automatically set the corresponding labels.

    So, if the key doesn't have a period, the named property of the root widget
    will be set to the corresponding value. If there is a period, the named
    property of the widget with the id listed before the period will be set to
    the corresponding value.

    .. versionadded:: 2.0.0
    """
    def refresh_view_attrs(self, rv, index, data): # -> None:
        ...
    


class RecycleDataAdapter(EventDispatcher):
    '''The class that converts data to a view.

    --- Internal details ---
    A view can have 3 states.

        * It can be completely in sync with the data, which
          occurs when the view is displayed. These are stored in :attr:`views`.
        * It can be dirty, which occurs when the view is in sync with the data,
          except for the size/pos parameters which is controlled by the layout.
          This occurs when the view is not currently displayed but the data has
          not changed. These views are stored in :attr:`dirty_views`.
        * Finally the view can be dead which occurs when the data changes and
          the view was not updated or when a view is just created. Such views
          are typically added to the internal cache.

    Typically what happens is that the layout manager lays out the data
    and then asks for views, using :meth:`set_visible_views`, for some specific
    data items that it displays.

    These views are gotten from the current views, dirty or global cache. Then
    depending on the view state :meth:`refresh_view_attrs` is called to bring
    the view up to date with the data (except for sizing parameters). Finally,
    the layout manager gets these views, updates their size and displays them.
    '''
    recycleview = ...
    views = ...
    dirty_views = ...
    _sizing_attrs = ...
    def __init__(self, **kwargs) -> None:
        """
        Fix for issue https://github.com/kivy/kivy/issues/5913:
        Scrolling RV A, then Scrolling RV B, content of A and B seemed
        to be getting mixed up
        """
        ...
    
    def attach_recycleview(self, rv): # -> None:
        '''Associates a :class:`~kivy.uix.recycleview.RecycleViewBehavior`
        with this instance. It is stored in :attr:`recycleview`.
        '''
        ...
    
    def detach_recycleview(self): # -> None:
        '''Removes the :class:`~kivy.uix.recycleview.RecycleViewBehavior`
        associated with this instance and clears :attr:`recycleview`.
        '''
        ...
    
    def create_view(self, index, data_item, viewclass): # -> None:
        '''(internal) Creates and initializes the view for the data at `index`.

        The returned view is synced with the data, except for the pos/size
        information.
        '''
        ...
    
    def get_view(self, index, data_item, viewclass): # -> None:
        '''(internal) Returns a view instance for the data at `index`

        It looks through the various caches and finally creates a view if it
        doesn't exist. The returned view is synced with the data, except for
        the pos/size information.

        If found in the cache it's removed from the source
        before returning. It doesn't check the current views.
        '''
        ...
    
    def refresh_view_attrs(self, index, data_item, view): # -> None:
        '''(internal) Syncs the view and brings it up to date with the data.

        This method calls :meth:`RecycleDataViewBehavior.refresh_view_attrs`
        if the view inherits from :class:`RecycleDataViewBehavior`. See that
        method for more details.

        .. note::
            Any sizing and position info is skipped when syncing with the data.
        '''
        ...
    
    def refresh_view_layout(self, index, layout, view, viewport): # -> None:
        '''Updates the sizing information of the view.

        viewport is in coordinates of the layout manager.

        This method calls :meth:`RecycleDataViewBehavior.refresh_view_attrs`
        if the view inherits from :class:`RecycleDataViewBehavior`. See that
        method for more details.

        .. note::
            Any sizing and position info is skipped when syncing with the data.
        '''
        ...
    
    def make_view_dirty(self, view, index): # -> None:
        '''(internal) Used to flag this view as dirty, ready to be used for
        others. See :meth:`make_views_dirty`.
        '''
        ...
    
    def make_views_dirty(self): # -> None:
        '''Makes all the current views dirty.

        Dirty views are still in sync with the corresponding data. However, the
        size information may go out of sync. Therefore a dirty view can be
        reused by the same index by just updating the sizing information.

        Once the underlying data of this index changes, the view should be
        removed from the dirty views and moved to the global cache with
        :meth:`invalidate`.

        This is typically called when the layout manager needs to re-layout all
        the data.
        '''
        ...
    
    def invalidate(self): # -> None:
        '''Moves all the current views into the global cache.

        As opposed to making a view dirty where the view is in sync with the
        data except for sizing information, this will completely disconnect the
        view from the data, as it is assumed the data has gone out of sync with
        the view.

        This is typically called when the data changes.
        '''
        ...
    
    def set_visible_views(self, indices, data, viewclasses): # -> tuple[list[Any], list[Any], dict_items[Any, Any]]:
        '''Gets a 3-tuple of the new, remaining, and old views for the current
        viewport.

        The new views are synced to the data except for the size/pos
        properties.
        The old views need to be removed from the layout, and the new views
        added.

        The new views are not necessarily *new*, but are all the currently
        visible views.
        '''
        ...
    
    def get_visible_view(self, index): # -> None:
        '''Returns the currently visible view associated with ``index``.

        If no view is currently displayed for ``index`` it returns ``None``.
        '''
        ...
    


