"""
This type stub file was generated by pyright.
"""

__version__ = ...
def main(args: list[str] | None = ...) -> int:
    """This is an internal API only meant for use by pip's own console scripts.

    For additional details, see https://github.com/pypa/pip/issues/7498.
    """
    ...

