"""
This type stub file was generated by pyright.
"""

import re
import sys
import ipaddress

"""The match_hostname() function from Python 3.3.3, essential when using SSL."""
__version__ = ...
class CertificateError(ValueError):
    ...


def match_hostname(cert, hostname): # -> None:
    """Verify that *cert* (in decoded format as returned by
    SSLSocket.getpeercert()) matches the *hostname*.  RFC 2818 and RFC 6125
    rules are followed, but IP addresses are not accepted for *hostname*.

    CertificateError is raised on failure. On success, the function
    returns nothing.
    """
    ...

