"""
This type stub file was generated by pyright.
"""

from importlib.metadata import entry_points

"""
    pygments.plugin
    ~~~~~~~~~~~~~~~

    Pygments plugin interface.

    lexer plugins::

        [pygments.lexers]
        yourlexer = yourmodule:YourLexer

    formatter plugins::

        [pygments.formatters]
        yourformatter = yourformatter:YourFormatter
        /.ext = yourformatter:YourFormatter

    As you can see, you can define extensions for the formatter
    with a leading slash.

    syntax plugins::

        [pygments.styles]
        yourstyle = yourstyle:YourStyle

    filter plugin::

        [pygments.filter]
        yourfilter = yourfilter:YourFilter


    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""
LEXER_ENTRY_POINT = ...
FORMATTER_ENTRY_POINT = ...
STYLE_ENTRY_POINT = ...
FILTER_ENTRY_POINT = ...
def iter_entry_points(group_name): # -> EntryPoints:
    ...

def find_plugin_lexers(): # -> Generator[Any, Any, None]:
    ...

def find_plugin_formatters(): # -> Generator[tuple[str | Any, Any], Any, None]:
    ...

def find_plugin_styles(): # -> Generator[tuple[str | Any, Any], Any, None]:
    ...

def find_plugin_filters(): # -> Generator[tuple[str | Any, Any], Any, None]:
    ...

