"""
This type stub file was generated by pyright.
"""

import re
from pip._vendor.pygments.token import Comment, Error, Keyword, Name, String, Whitespace, string_to_tokentype
from pip._vendor.pygments.filter import Filter
from pip._vendor.pygments.util import ClassNotFound, OptionError, get_bool_opt, get_choice_opt, get_int_opt, get_list_opt
from pip._vendor.pygments.plugin import find_plugin_filters

"""
    pygments.filters
    ~~~~~~~~~~~~~~~~

    Module containing filter lookup functions and default
    filters.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
"""
def find_filter_class(filtername): # -> Any | None:
    """Lookup a filter by name. Return None if not found."""
    ...

def get_filter_by_name(filtername, **options): # -> Any:
    """Return an instantiated filter.

    Options are passed to the filter initializer if wanted.
    Raise a ClassNotFound if not found.
    """
    ...

def get_all_filters(): # -> Generator[str | Any, Any, None]:
    """Return a generator of all filter names."""
    ...

class CodeTagFilter(Filter):
    """Highlight special code tags in comments and docstrings.

    Options accepted:

    `codetags` : list of strings
       A list of strings that are flagged as code tags.  The default is to
       highlight ``XXX``, ``TODO``, ``FIXME``, ``BUG`` and ``NOTE``.

    .. versionchanged:: 2.13
       Now recognizes ``FIXME`` by default.
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class SymbolFilter(Filter):
    """Convert mathematical symbols such as \\<longrightarrow> in Isabelle
    or \\longrightarrow in LaTeX into Unicode characters.

    This is mostly useful for HTML or console output when you want to
    approximate the source rendering you'd see in an IDE.

    Options accepted:

    `lang` : string
       The symbol language. Must be one of ``'isabelle'`` or
       ``'latex'``.  The default is ``'isabelle'``.
    """
    latex_symbols = ...
    isabelle_symbols = ...
    lang_map = ...
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, str] | tuple[Any, Any], Any, None]:
        ...
    


class KeywordCaseFilter(Filter):
    """Convert keywords to lowercase or uppercase or capitalize them, which
    means first letter uppercase, rest lowercase.

    This can be useful e.g. if you highlight Pascal code and want to adapt the
    code to your styleguide.

    Options accepted:

    `case` : string
       The casing to convert keywords to. Must be one of ``'lower'``,
       ``'upper'`` or ``'capitalize'``.  The default is ``'lower'``.
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class NameHighlightFilter(Filter):
    """Highlight a normal Name (and Name.*) token with a different token type.

    Example::

        filter = NameHighlightFilter(
            names=['foo', 'bar', 'baz'],
            tokentype=Name.Function,
        )

    This would highlight the names "foo", "bar" and "baz"
    as functions. `Name.Function` is the default token type.

    Options accepted:

    `names` : list of strings
      A list of names that should be given the different token type.
      There is no default.
    `tokentype` : TokenType or string
      A token type or a string containing a token type name that is
      used for highlighting the strings in `names`.  The default is
      `Name.Function`.
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[_TokenType | Any, Any] | tuple[Any, Any], Any, None]:
        ...
    


class ErrorToken(Exception):
    ...


class RaiseOnErrorTokenFilter(Filter):
    """Raise an exception when the lexer generates an error token.

    Options accepted:

    `excclass` : Exception class
      The exception class to raise.
      The default is `pygments.filters.ErrorToken`.

    .. versionadded:: 0.8
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class VisibleWhitespaceFilter(Filter):
    """Convert tabs, newlines and/or spaces to visible characters.

    Options accepted:

    `spaces` : string or bool
      If this is a one-character string, spaces will be replaces by this string.
      If it is another true value, spaces will be replaced by ``·`` (unicode
      MIDDLE DOT).  If it is a false value, spaces will not be replaced.  The
      default is ``False``.
    `tabs` : string or bool
      The same as for `spaces`, but the default replacement character is ``»``
      (unicode RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK).  The default value
      is ``False``.  Note: this will not work if the `tabsize` option for the
      lexer is nonzero, as tabs will already have been expanded then.
    `tabsize` : int
      If tabs are to be replaced by this filter (see the `tabs` option), this
      is the total number of characters that a tab should be expanded to.
      The default is ``8``.
    `newlines` : string or bool
      The same as for `spaces`, but the default replacement character is ``¶``
      (unicode PILCROW SIGN).  The default value is ``False``.
    `wstokentype` : bool
      If true, give whitespace the special `Whitespace` token type.  This allows
      styling the visible whitespace differently (e.g. greyed out), but it can
      disrupt background colors.  The default is ``True``.

    .. versionadded:: 0.8
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, Any], Any, None]:
        ...
    


class GobbleFilter(Filter):
    """Gobbles source code lines (eats initial characters).

    This filter drops the first ``n`` characters off every line of code.  This
    may be useful when the source code fed to the lexer is indented by a fixed
    amount of space that isn't desired in the output.

    Options accepted:

    `n` : int
       The number of characters to gobble.

    .. versionadded:: 1.2
    """
    def __init__(self, **options) -> None:
        ...
    
    def gobble(self, value, left): # -> tuple[Any, Literal[0]] | tuple[Literal[''], Any]:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, str], Any, None]:
        ...
    


class TokenMergeFilter(Filter):
    """Merges consecutive tokens with the same token type in the output
    stream of a lexer.

    .. versionadded:: 1.2
    """
    def __init__(self, **options) -> None:
        ...
    
    def filter(self, lexer, stream): # -> Generator[tuple[Any, Any | None], Any, None]:
        ...
    


FILTERS = ...
