"""
This type stub file was generated by pyright.
"""

import datetime
import logging
import os
import re
import socket
import warnings
import ssl
from socket import error as SocketError, timeout as SocketTimeout
from .packages import six
from .packages.six.moves.http_client import HTTPConnection as _HTTPConnection, HTTPException
from .util.proxy import create_proxy_ssl_context
from ._collections import HTTPHeaderDict
from ._version import __version__
from .exceptions import ConnectTimeoutError, NewConnectionError, SubjectAltNameWarning, SystemTimeWarning
from .util import SKIPPABLE_HEADERS, SKIP_HEADER, connection
from .util.ssl_ import assert_fingerprint, create_urllib3_context, is_ipaddress, resolve_cert_reqs, resolve_ssl_version, ssl_wrap_socket
from .util.ssl_match_hostname import CertificateError, match_hostname

BaseSSLError = ...
ConnectionError = ...
BrokenPipeError = ...
log = ...
port_by_scheme = ...
RECENT_DATE = ...
_CONTAINS_CONTROL_CHAR_RE = ...
class HTTPConnection(_HTTPConnection):
    """
    Based on :class:`http.client.HTTPConnection` but provides an extra constructor
    backwards-compatibility layer between older and newer Pythons.

    Additional keyword parameters are used to configure attributes of the connection.
    Accepted parameters include:

    - ``strict``: See the documentation on :class:`urllib3.connectionpool.HTTPConnectionPool`
    - ``source_address``: Set the source address for the current connection.
    - ``socket_options``: Set specific options on the underlying socket. If not specified, then
      defaults are loaded from ``HTTPConnection.default_socket_options`` which includes disabling
      Nagle's algorithm (sets TCP_NODELAY to 1) unless the connection is behind a proxy.

      For example, if you wish to enable TCP Keep Alive in addition to the defaults,
      you might pass:

      .. code-block:: python

         HTTPConnection.default_socket_options + [
             (socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1),
         ]

      Or you may want to disable the defaults by passing an empty list (e.g., ``[]``).
    """
    default_port = ...
    default_socket_options = ...
    is_verified = ...
    proxy_is_verified = ...
    def __init__(self, *args, **kw) -> None:
        ...
    
    @property
    def host(self):
        """
        Getter method to remove any trailing dots that indicate the hostname is an FQDN.

        In general, SSL certificates don't include the trailing dot indicating a
        fully-qualified domain name, and thus, they don't validate properly when
        checked against a domain name that includes the dot. In addition, some
        servers may not expect to receive the trailing dot when provided.

        However, the hostname with trailing dot is critical to DNS resolution; doing a
        lookup with the trailing dot will properly only resolve the appropriate FQDN,
        whereas a lookup without a trailing dot will search the system's search domain
        list. Thus, it's important to keep the original host around for use only in
        those cases where it's appropriate (i.e., when doing DNS lookup to establish the
        actual TCP connection across which we're going to send HTTP requests).
        """
        ...
    
    @host.setter
    def host(self, value): # -> None:
        """
        Setter for the `host` property.

        We assume that only urllib3 uses the _dns_host attribute; httplib itself
        only uses `host`, and it seems reasonable that other libraries follow suit.
        """
        ...
    
    def connect(self): # -> None:
        ...
    
    def putrequest(self, method, url, *args, **kwargs):
        """ """
        ...
    
    def putheader(self, header, *values): # -> None:
        """ """
        ...
    
    def request(self, method, url, body=..., headers=...): # -> None:
        ...
    
    def request_chunked(self, method, url, body=..., headers=...): # -> None:
        """
        Alternative to the common request method, which sends the
        body with chunked encoding and not as one block
        """
        ...
    


class HTTPSConnection(HTTPConnection):
    """
    Many of the parameters to this constructor are passed to the underlying SSL
    socket by means of :py:func:`urllib3.util.ssl_wrap_socket`.
    """
    default_port = ...
    cert_reqs = ...
    ca_certs = ...
    ca_cert_dir = ...
    ca_cert_data = ...
    ssl_version = ...
    assert_fingerprint = ...
    tls_in_tls_required = ...
    def __init__(self, host, port=..., key_file=..., cert_file=..., key_password=..., strict=..., timeout=..., ssl_context=..., server_hostname=..., **kw) -> None:
        ...
    
    def set_cert(self, key_file=..., cert_file=..., cert_reqs=..., key_password=..., ca_certs=..., assert_hostname=..., assert_fingerprint=..., ca_cert_dir=..., ca_cert_data=...): # -> None:
        """
        This method should only be called once, before the connection is used.
        """
        ...
    
    def connect(self): # -> None:
        ...
    


class DummyConnection:
    """Used to detect a failed ConnectionCls import."""
    ...


if not ssl:
    HTTPSConnection = ...
VerifiedHTTPSConnection = HTTPSConnection
