"""
This type stub file was generated by pyright.
"""

from kivy.uix.recyclelayout import RecycleLayout
from kivy.uix.boxlayout import BoxLayout

"""
RecycleBoxLayout
================

.. versionadded:: 1.10.0

.. warning::
    This module is highly experimental, its API may change in the future and
    the documentation is not complete at this time.

The RecycleBoxLayout is designed to provide a
:class:`~kivy.uix.boxlayout.BoxLayout` type layout when used with the
:class:`~kivy.uix.recycleview.RecycleView` widget. Please refer to the
:mod:`~kivy.uix.recycleview` module documentation for more information.

"""
__all__ = ('RecycleBoxLayout', )
class RecycleBoxLayout(RecycleLayout, BoxLayout):
    _rv_positions = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def compute_layout(self, data, flags): # -> None:
        ...
    
    def get_view_index_at(self, pos): # -> int:
        ...
    
    def compute_visible_views(self, data, viewport): # -> list[Any] | list[int]:
        ...
    


