"""
This type stub file was generated by pyright.
"""

from datetime import datetime, timezone
from typing import TYPE_CHECKING
from pip._vendor.cachecontrol.cache import BaseCache
from redis import Redis

if TYPE_CHECKING:
    ...
class RedisCache(BaseCache):
    def __init__(self, conn: Redis[bytes]) -> None:
        ...
    
    def get(self, key: str) -> bytes | None:
        ...
    
    def set(self, key: str, value: bytes, expires: int | datetime | None = ...) -> None:
        ...
    
    def delete(self, key: str) -> None:
        ...
    
    def clear(self) -> None:
        """Helper for clearing all the keys in a database. Use with
        caution!"""
        ...
    
    def close(self) -> None:
        """Redis uses connection pooling, no need to close the connection."""
        ...
    


