"""
This type stub file was generated by pyright.
"""

import glob
import os.path
import sys

"""
pip._vendor is for vendoring dependencies of pip to prevent needing pip to
depend on something external.

Files inside of pip._vendor should be considered immutable and should only be
updated to versions from upstream.
"""
DEBUNDLED = ...
WHEEL_DIR = ...
def vendored(modulename): # -> None:
    ...

if DEBUNDLED:
    ...
