"""
This type stub file was generated by pyright.
"""

import importlib.resources as resources

"""This is a subpackage because the directory is on sys.path for _in_process.py

The subpackage should stay as empty as possible to avoid shadowing modules that
the backend might import.
"""
