"""
This type stub file was generated by pyright.
"""

import logging
from collections import OrderedDict
from pip._vendor.packaging.utils import canonicalize_name
from pip._internal.req.req_install import InstallRequirement

logger = ...
class RequirementSet:
    def __init__(self, check_supported_wheels: bool = ...) -> None:
        """Create a RequirementSet."""
        ...
    
    def __str__(self) -> str:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def add_unnamed_requirement(self, install_req: InstallRequirement) -> None:
        ...
    
    def add_named_requirement(self, install_req: InstallRequirement) -> None:
        ...
    
    def has_requirement(self, name: str) -> bool:
        ...
    
    def get_requirement(self, name: str) -> InstallRequirement:
        ...
    
    @property
    def all_requirements(self) -> list[InstallRequirement]:
        ...
    
    @property
    def requirements_to_install(self) -> list[InstallRequirement]:
        """Return the list of requirements that need to be installed.

        TODO remove this property together with the legacy resolver, since the new
             resolver only returns requirements that need to be installed.
        """
        ...
    


