"""
This type stub file was generated by pyright.
"""

from kivy.core.clipboard import ClipboardBase

'''
Clipboard ext: base class for external command clipboards
'''
__all__ = ('ClipboardExternalBase', )
class ClipboardExternalBase(ClipboardBase):
    def get(self, mimetype=...):
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_cutbuffer(self):
        ...
    
    def set_cutbuffer(self, data): # -> None:
        ...
    
    def get_types(self): # -> list[str]:
        ...
    


