"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from kivy.core.clipboard import ClipboardBase

'''
Clipboard Gtk3: an implementation of the Clipboard using Gtk3.
'''
__all__ = ('ClipboardGtk3', )
if platform != 'linux':
    ...
clipboard = ...
class ClipboardGtk3(ClipboardBase):
    _is_init = ...
    def init(self): # -> None:
        ...
    
    def get(self, mimetype=...): # -> Literal['']:
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[str]:
        ...
    


