"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from kivy.core.clipboard._clipboard_ext import ClipboardExternalBase

'''
Clipboard xclip: an implementation of the Clipboard using xclip
command line tool.
'''
__all__ = ('ClipboardXclip', )
if platform != 'linux':
    ...
p = ...
class ClipboardXclip(ClipboardExternalBase):
    ...


