"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from kivy.core.clipboard._clipboard_ext import ClipboardExternalBase

'''
Clipboard xsel: an implementation of the Clipboard using xsel command line
                tool.
'''
__all__ = ('ClipboardXsel', )
if platform != 'linux':
    ...
p = ...
class ClipboardXsel(ClipboardExternalBase):
    ...


