"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from kivy.core.clipboard import ClipboardBase

'''
Clipboard Dbus: an implementation of the Clipboard using dbus and klipper.
'''
__all__ = ('ClipboardDbusKlipper', )
if platform != 'linux':
    ...
bus = ...
proxy = ...
class ClipboardDbusKlipper(ClipboardBase):
    _is_init = ...
    def init(self): # -> None:
        ...
    
    def get(self, mimetype=...): # -> str:
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[str]:
        ...
    


