"""
This type stub file was generated by pyright.
"""

from kivy.utils import deprecated, platform
from kivy.core.clipboard import ClipboardBase

'''
Clipboard Pygame: an implementation of the Clipboard using pygame.scrap.

.. warning::

    Pygame has been deprecated and will be removed in the release after Kivy
    1.11.0.
'''
__all__ = ('ClipboardPygame', )
if platform not in ('win', 'linux', 'macosx'):
    ...
class ClipboardPygame(ClipboardBase):
    _is_init = ...
    _types = ...
    _aliases = ...
    @deprecated(msg='Pygame has been deprecated and will be removed after 1.11.0')
    def __init__(self, *largs, **kwargs) -> None:
        ...
    
    def init(self): # -> None:
        ...
    
    def get(self, mimetype=...):
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self):
        ...
    


