"""
This type stub file was generated by pyright.
"""

from kivy.core.clipboard import ClipboardBase
from kivy.utils import platform

'''
Clipboard OsX: implementation of clipboard using Appkit
'''
__all__ = ('ClipboardNSPaste', )
if platform != 'macosx':
    ...
NSPasteboard = ...
NSString = ...
class ClipboardNSPaste(ClipboardBase):
    def __init__(self) -> None:
        ...
    
    def get(self, mimetype=...): # -> Literal['']:
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[str]:
        ...
    


