"""
This type stub file was generated by pyright.
"""

from kivy.utils import platform
from kivy.core.clipboard import ClipboardBase

'''
Clipboard SDL2: an implementation of the Clipboard using sdl2.
'''
__all__ = ('ClipboardSDL2', )
if platform not in ('win', 'linux', 'macosx', 'android', 'ios'):
    ...
class ClipboardSDL2(ClipboardBase):
    def get(self, mimetype): # -> Literal['']:
        ...
    
    def put(self, data=..., mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[str]:
        ...
    


