"""
This type stub file was generated by pyright.
"""

from kivy.core.clipboard import ClipboardBase

'''
Clipboard Dummy: an internal implementation that does not use the system
clipboard.
'''
__all__ = ('ClipboardDummy', )
class ClipboardDummy(ClipboardBase):
    def __init__(self) -> None:
        ...
    
    def get(self, mimetype=...): # -> None:
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[Any]:
        ...
    


