"""
This type stub file was generated by pyright.
"""

from kivy.core.clipboard import ClipboardBase

'''
Clipboard Android
=================

Android implementation of Clipboard provider, using Pyjnius.
'''
__all__ = ('ClipboardAndroid', )
AndroidString = ...
PythonActivity = ...
Context = ...
VER = ...
sdk = ...
class ClipboardAndroid(ClipboardBase):
    def __init__(self) -> None:
        ...
    
    def get(self, mimetype=...): # -> bytes:
        ...
    
    def put(self, data, mimetype=...): # -> None:
        ...
    
    def get_types(self): # -> list[Any]:
        ...
    


