"""
This type stub file was generated by pyright.
"""

import io
from typing import Any, IO, Mapping, TYPE_CHECKING, cast
from pip._vendor import msgpack
from pip._vendor.requests.structures import CaseInsensitiveDict
from pip._vendor.urllib3 import HTTPResponse
from pip._vendor.requests import PreparedRequest

if TYPE_CHECKING:
    ...
class Serializer:
    serde_version = ...
    def dumps(self, request: PreparedRequest, response: HTTPResponse, body: bytes | None = ...) -> bytes:
        ...
    
    def serialize(self, data: dict[str, Any]) -> bytes:
        ...
    
    def loads(self, request: PreparedRequest, data: bytes, body_file: IO[bytes] | None = ...) -> HTTPResponse | None:
        ...
    
    def prepare_response(self, request: PreparedRequest, cached: Mapping[str, Any], body_file: IO[bytes] | None = ...) -> HTTPResponse | None:
        """Verify our vary headers match and construct a real urllib3
        HTTPResponse object.
        """
        ...
    


